// flow-typed signature: 43282bf861fc0b93bc9def8e79550cd5
// flow-typed version: <<STUB>>/key-string_v^0.4.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'key-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'key-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'key-string/detectKeyString' {
  declare module.exports: any;
}

declare module 'key-string/keyStringMap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'key-string/detectKeyString.js' {
  declare module.exports: $Exports<'key-string/detectKeyString'>;
}
declare module 'key-string/index' {
  declare module.exports: $Exports<'key-string'>;
}
declare module 'key-string/index.js' {
  declare module.exports: $Exports<'key-string'>;
}
declare module 'key-string/keyStringMap.js' {
  declare module.exports: $Exports<'key-string/keyStringMap'>;
}
